// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP4AXV79KyIIJyqivyrSMi51HSFp4a7SE',
    appId: '1:819412544330:web:5115d6b4d562313f662fb3',
    messagingSenderId: '819412544330',
    projectId: 'rick-and-morty-universe-c04b0',
    authDomain: 'rick-and-morty-universe-c04b0.firebaseapp.com',
    storageBucket: 'rick-and-morty-universe-c04b0.appspot.com',
    measurementId: 'G-0V1FDNNHXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3ZXugloE2wbNn5YpW21QSwy9QWurjPI8',
    appId: '1:819412544330:android:d692bff4ed5d7ed6662fb3',
    messagingSenderId: '819412544330',
    projectId: 'rick-and-morty-universe-c04b0',
    storageBucket: 'rick-and-morty-universe-c04b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb16kr3Odioq-rD7DkB2VThF1Px63zdeA',
    appId: '1:819412544330:ios:bc61611ea2e5f77d662fb3',
    messagingSenderId: '819412544330',
    projectId: 'rick-and-morty-universe-c04b0',
    storageBucket: 'rick-and-morty-universe-c04b0.appspot.com',
    iosBundleId: 'com.devx.ricknmorty.rickMortyUniverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb16kr3Odioq-rD7DkB2VThF1Px63zdeA',
    appId: '1:819412544330:ios:719bc084300e2ea1662fb3',
    messagingSenderId: '819412544330',
    projectId: 'rick-and-morty-universe-c04b0',
    storageBucket: 'rick-and-morty-universe-c04b0.appspot.com',
    iosBundleId: 'com.devx.ricknmorty.rickMortyUniverse.RunnerTests',
  );
}
