// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAopiQfiPk3DarnjFjBwIR59Fi7BmREws8',
    appId: '1:156839349144:web:6841a949936f854fe039ed',
    messagingSenderId: '156839349144',
    projectId: 'rick-morty-universe',
    authDomain: 'rick-morty-universe.firebaseapp.com',
    storageBucket: 'rick-morty-universe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmyShk3qE0qELIZsgYh5QzPcfq1Pz_Z5Y',
    appId: '1:156839349144:android:dca8cc66cd7b3fefe039ed',
    messagingSenderId: '156839349144',
    projectId: 'rick-morty-universe',
    storageBucket: 'rick-morty-universe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLTBAiIl_4mQ2xUPl1G6IUg6j3KFnDtvs',
    appId: '1:156839349144:ios:0508a5a54387335ae039ed',
    messagingSenderId: '156839349144',
    projectId: 'rick-morty-universe',
    storageBucket: 'rick-morty-universe.appspot.com',
    iosBundleId: 'com.devx.ricknmorty.rickMortyUniverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLTBAiIl_4mQ2xUPl1G6IUg6j3KFnDtvs',
    appId: '1:156839349144:ios:7d2c12450f04b4e2e039ed',
    messagingSenderId: '156839349144',
    projectId: 'rick-morty-universe',
    storageBucket: 'rick-morty-universe.appspot.com',
    iosBundleId: 'com.devx.ricknmorty.rickMortyUniverse.RunnerTests',
  );
}
