#name: "Build & Release - iOS"
#
#on:
#  push:
#    tags:
#      - v*
#
#jobs:
#  build:
#    name: "Build & Release"
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-java@v3
#        with:
#          java-version: "17.x"
#      - uses: subosito/flutter-action@v2
#        with:
#          channel: "stable"
#      - run: flutter pub get
#      - run: flutter test
#      - run:  |
#          flutter build ios --no-codesign
#          cd build/ios/iphoneos
#          mkdir Payload
#          ln -s ../Runner.app
#          cd ..
#          zip -r app.ipa Payload
#
#      - name: Push to Releases
#        uses: ncipollo/release-action@v1
#        with:
#          artifact: "build/ios/iphoneos/app.ipa"
#          tag: ios.v1.0.${{github.run_number}}
#          token: ${{secrets.GH_TOKEN}}