name: "Build & Release - Android"

on:
  workflow_run:
    workflows: [ "Build Analyze and Test" ]
    branches: [ master ]
    types:
      - completed

jobs:
  build:
    name: "Build & Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/app-release.apk"
          tag: v1.0.${{github.run_number}}
          token: ${{secrets.GH_TOKEN}}

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.FIREBASE_SERVICE_ACCOUNT}}
          groups: internal-testing
          file: build/app/outputs/apk/release/app-release.apk